MusicRepository/MusicRepository/Models/TrackViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicRepository.Models
{
    public class TrackViewModel
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string AlbumName { get; set; }
        [Range(0.1, 5)]
        public double Rate { get; set; }
        public List<SelectListItem> list { get; set; } 
    }

    public class TrackDetail
    {
        public int Id { get; set; }
        public int AlbumId { get; set; }
        public int AutorId { get; set; }
        public string TrackName { get; set; }
        public string AlbumName { get; set; }
        public string AutorName { get; set; }
        public double Rate { get; set; }
    }

    public class TrackListViewModel
    {
        public List<TrackDetail> List { get; set; }
        public PagingInfo PagingInfo { get; set; } 
    }
}

MusicRepository/MusicRepository/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.EnterpriseServices.Internal;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MusicRepository.Models;

namespace MusicRepository.Controllers
{
    public class AlbumsController : Controller
    {
        private MusicContext db = new MusicContext();
        private int PageSize = 5;
        // GET: Albums
        public ActionResult Index(int page=1)
        {
            AlbumListViewModel model = new AlbumListViewModel
            {
                Albums = db.Albums.OrderBy(m => m.AlbumId).Skip((page - 1)*PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = db.Albums.Count()
                }
            };
            return View(model);
        }

        // GET: Albums/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (db.Albums.Find(id) == null)
            {
                return HttpNotFound();
            }
            ViewBag.Album = GetAlbum(id);
            return View(AlbumDetailsViewModelInitializer((int)id));
        }

        // GET: Albums/Create
        public ActionResult Create(int? Autorid=null)
        {
            ViewBag.Album = new Album();
            ViewBag.Title = "Create";
            return View((Autorid==null)? EditViewModelInitializer(): EditViewModelInitializer((int)Autorid));
        }
        
        // GET: Albums/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            ViewBag.Title = "Edit";
            ViewBag.Album = album;
            return View("Create", EditViewModelInitializer(album));
        }

        // POST: Albums/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AlbumViewModel model, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                bool newAlbum = false;
                if (db.Albums.Find(model.Id) == null)
                {
                    newAlbum = true;
                }
                Album album = ApplyItemChanges(model);
                if (image != null)
                {
                    AddImageToAlbum(album, image);
                }
                if (newAlbum)
                {
                    db.Albums.Add(album);
                }
                else
                {
                    db.Entry(album).State = EntityState.Modified;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET: Albums/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (db.Albums.Find(id) == null)
            {
                return HttpNotFound();
            }
            if (db.Tracks.FirstOrDefault(m => m.AlbumId == id) != null)
            {
                return View("DeleteWarning", AlbumDetailsViewModelInitializer((int)id));
            }
            return View(GetAlbum(id));
        }

        // POST: Albums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Album album = db.Albums.Find(id);
            db.Albums.Remove(album);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public PartialViewResult AlbumSummary(int id)
        {
            Album album = db.Albums.FirstOrDefault(m => m.AlbumId == id);
            ViewBag.Autor = db.Autors.FirstOrDefault(m => m.AutorId == album.AutorId).Name;
            ViewBag.Tracks = db.Tracks.Where(m => m.AlbumId == album.AlbumId).ToList().Count;
            return PartialView(album);
        }

        public FileContentResult GetImage(int id)
        {
            Album album = db.Albums.FirstOrDefault(m => m.AlbumId == id);
            if (album != null)
            {
                return File(album.ImageData, album.ImageMimeType);
            }
            else
            {
                return null;
            }
        }


        //____________________________________________________________________
        //private methods
        private Album GetAlbum(int? id)
        {
            if (id != null)
            {
                return db.Albums.Find(id);
            }
            else
            {
                return new Album();
            }
        }

        private Autor GetAutor(int id)
        {
            return db.Autors.Find(id);
        }

        private List<Track> GetTracksList(int id)
        {
            return db.Tracks.Where(a => a.AlbumId == id).ToList();
        }

        private List<Autor> GetAutorsList()
        {
            return db.Autors.ToList();
        } 
        private AlbumDetails AlbumDetailsViewModelInitializer(int id)
        {
            Album album = GetAlbum(id);
            AlbumDetails result = new AlbumDetails
            {
                AlbumName = album.Name,
                AutorId = album.AutorId,
                AutorName = GetAlbum(album.AutorId).Name,
                Description = album.Description,
                Id = id,
                Rate = album.Rate,
                tracks = GetTracksList(id)
            };
            return result;
        }

        private AlbumViewModel EditViewModelInitializer(Album album)
        {
            AlbumViewModel result = new AlbumViewModel
            {
                Description = album.Description,
                Id = album.AlbumId,
                list = new List<SelectListItem>(),
                Name = album.Name,
                AutorName = GetAutor(album.AutorId).Name,
                Rate = album.Rate
            };
            foreach (var item in GetAutorsList())
            {
                result.list.Add(new SelectListItem {Text = item.Name});
            }
            return result;
        }

        private AlbumViewModel EditViewModelInitializer(int id)
        {
            AlbumViewModel result = new AlbumViewModel
            {
                list = new List<SelectListItem>(),
                AutorName = GetAutor(id).Name
            };
            foreach (var item in GetAutorsList())
            {
                result.list.Add(new SelectListItem { Text = item.Name });
            }
            return result;
        }
        private AlbumViewModel EditViewModelInitializer()
        {
            AlbumViewModel result = new AlbumViewModel
            {
                list = new List<SelectListItem>()
            };
            foreach (var item in GetAutorsList())
            {
                result.list.Add(new SelectListItem { Text = item.Name });
            }
            return result;
        }

        private void AddImageToAlbum(Album album, HttpPostedFileBase image)
        {
            album.ImageMimeType = image.ContentType;
            album.ImageData = new byte[image.ContentLength];
            image.InputStream.Read(album.ImageData, 0, image.ContentLength);
        }

        private Album ApplyItemChanges(AlbumViewModel model)
        {
            Album result = GetAlbum(model.Id);
            if (result == null)
            {
                result=new Album();
            }
            result.Name = model.Name;
            result.Description = model.Description;
            result.Rate = model.Rate;
            result.AutorId = db.Autors.FirstOrDefault(a => a.Name == model.AutorName).AutorId;
            return result;
        }
    }
}

MusicRepository/MusicRepository/Controllers/AutorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;
using System.Web.Razor.Generator;
using MusicRepository.Models;

namespace MusicRepository.Controllers
{
    public class AutorsController : Controller
    {
        private MusicContext db = new MusicContext();
        private int PageSize=5;
        // GET: Autors
        public ActionResult Index(int page=1)
        {
            AutorListViewModel model = new AutorListViewModel
            {
                Autors = db.Autors.OrderBy(m => m.AutorId).Skip((page - 1)*PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = db.Autors.Count()
                }
            };
            return View(model);
        }

        // GET: Autors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (db.Autors.Find(id) == null)
            {
                return HttpNotFound();
            }
            ViewBag.Autor = GetAutor(id);
            return View(AutorDetailsViewModelInitializer((int)id));
        }

        // GET: Autors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Autors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Autor autor, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    AddAutorImage(autor, image);
                }
                AddItemToRepository(autor);
                return RedirectToAction("Index");
            }
            return View(autor);
        }

        // GET: Autors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (db.Autors.Find(id) == null)
            {
                return HttpNotFound();
            }
            return View(GetAutor(id));
        }

        // POST: Autors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Autor autor, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    AddAutorImage(autor, image);
                }
                SaveItemChanges(autor);
                return RedirectToAction("Index");
            }
            return View(autor);
        }

        // GET: Autors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (db.Albums.FirstOrDefault(a=>a.AutorId==id) != null)
            {
                return View("DeleteWarning", AutorDetailsViewModelInitializer((int)id));
            }
            if (db.Autors.Find(id) == null)
            {
                return HttpNotFound();
            }
            return View(GetAutor(id));
        }

        // POST: Autors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DeleteItem(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public FileContentResult GetImage(int autorid)
        {
            Autor autor = db.Autors.FirstOrDefault(m => m.AutorId == autorid);
            if (autor != null)
            {
                return File(autor.ImageData, autor.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        public PartialViewResult AutorSummary(int id)
        {
            int count = db.Albums.Where(m => m.AutorId == id).Count();
            ViewBag.Albums = count;
            return PartialView(GetAutor(id));
        }

        //_________________________________________________________________________________
        //private methods
        private Autor GetAutor(int? id)
        {
            if (id != null)
            {
                return db.Autors.Find(id);
            }
            else
            {
                return new Autor();
            }
        }

        private List<Album> GetAlbumsList(int autorId)
        {
            return db.Albums.Where(a => a.AutorId == autorId).ToList();
        }

        private AutorDetails AutorDetailsViewModelInitializer(int id)
        {
            Autor autor = GetAutor(id);
            AutorDetails result = new AutorDetails
            {
                albums = GetAlbumsList(id),
                Description = autor.Description,
                Id = id,
                Name = autor.Name
            };
            return result;
        }

        private void AddAutorImage(Autor autor, HttpPostedFileBase image)
        {
            autor.ImageMimeType = image.ContentType;
            autor.ImageData = new byte[image.ContentLength];
            image.InputStream.Read(autor.ImageData, 0, image.ContentLength);
        }
        private void AddItemToRepository(Autor autor)
        {
            db.Autors.Add(autor);
            db.SaveChanges();
        }

        private void SaveItemChanges(Autor autor)
        {
            db.Entry(autor).State=EntityState.Modified;
            db.SaveChanges();
        }

        private void DeleteItem(int id)
        {
            Autor autor = GetAutor(id);
            db.Autors.Remove(autor);
            db.SaveChanges();
        }
    }
}

MusicRepository/MusicRepository/Views/Tracks/Create.cshtml
@model MusicRepository.Models.TrackViewModel
<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Track</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model=>model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m=>m.AlbumName, htmlAttributes:new {@class="control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownListFor(m=>m.AlbumName, Model.list)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Rate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

MusicRepository/MusicRepository/Views/Tracks/Delete.cshtml
@model MusicRepository.Models.Track

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Track</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MusicRepository/MusicRepository/Views/Tracks/Details.cshtml
@model MusicRepository.Models.TrackDetail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Track</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            <b>Name</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrackName)
        </dd>
        <dt>
            <b>Album</b>
        </dt>
        <dd>
            @Html.ActionLink(Model.AlbumName, "Details/" + Model.AlbumId, "Albums")
        </dd>
        <dt>
            <b>Autor</b>
        </dt>
        <dd>
            @Html.ActionLink(Model.AutorName, "Details/" + Model.AutorId, "Autors")
        </dd>
        <dt>
            <b>Rate</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MusicRepository/MusicRepository/Views/Tracks/Index.cshtml
@using MusicRepository.HtmlHalpers
@model MusicRepository.Models.TrackListViewModel

@{
    ViewBag.Title = "Tracks List";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            <b>Autor</b>
        </th>
        <th>
            <b>Album</b>
        </th>
        <th>
            <b>Name</b>
        </th>
        <th>
            <b>Rate</b>
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.List) {
    <tr>
        <td>
            @Html.ActionLink(item.AutorName, "Details/" + item.AutorId, "Autors")
        </td>
        <td>
            @Html.ActionLink(item.AlbumName, "Details/" + item.AlbumId, "Albums")
        </td>
        <td>
            @Html.ActionLink(item.TrackName, "Details", new {id=item.Id})
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}
</table>
<div class="pager">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("Index",
    new { page = x }))
</div>